version: '3'

services:
    web:
        image: nginx:stable-alpine
        ports:
            - "8088:80"
        volumes:
            - ../../dist:/usr/share/nginx/html
            - ../nginx/default.conf:/etc/nginx/conf.d/default.conf
        links:
            - php
        networks:
            - app-network
    php:
        image: php:7-fpm-alpine
        volumes:
            - ../../dist:/var/www/html
        networks:
            - app-network

networks:
    app-network:
        driver: bridge
        ipam:
            config:
                - subnet: 172.28.0.0/24